import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <section className='max-w-6xl  mx-auto p-6 bg-white '>
          <Navbar />
          <div className='mt-8'>
            {children}
          </div>
        </section>
      </body>
    </html>
  )
}
